import json, re

with open('all_raw_texts.txt', 'r', encoding='utf-8') as f:
    lines = [l.strip() for l in f.readlines() if l.strip()]

unique = sorted(set(lines))
print('Total unique: %d' % len(unique))

cats = {}
for raw in unique:
    rl = raw.lower()
    cat = 'OTHER'
    
    if 'sands of time' in rl: cat = 'Unique: Sands of Time'
    elif 'thaumaturgical' in rl: cat = 'Unique: Thaumaturgical Dynamism'
    elif 'unravelling' in rl: cat = 'Unique: Unravelling'
    elif 'demonflame' in rl: cat = 'Unique: Demonflame'
    elif 'decimating' in rl: cat = 'Unique: Decimating Strike'
    elif 'walk the paths' in rl: cat = 'Unique: Walk the Paths Not Taken'
    elif 'crushing blow' in rl: cat = 'Unique: Crushing Blows'
    elif 'inevitable critical' in rl: cat = 'Unique: Inevitable Critical'
    elif 'passive skill point' in rl: cat = 'Grants: Passive Skill Point'
    elif 'additional skill slot' in rl: cat = 'Grants: Additional Skill Slot'
    elif 'grant skill:' in rl or 'grants skill:' in rl: cat = 'Grants: A Skill'
    elif 'allies' in rl and 'presence' in rl: cat = 'Presence: Allies in Presence'
    elif 'in your presence' in rl: cat = 'Presence: In your Presence effects'
    elif 'presence area' in rl: cat = 'Presence Area'
    elif 'tame beast' in rl or 'tamed' in rl: cat = 'Minion: Tame Beast'
    elif 'minion' in rl or 'summon' in rl or 'hound' in rl: cat = 'Minion: Summon/Minion'
    elif 'ballista' in rl: cat = 'Skill: Ballista'
    elif 'offering' in rl: cat = 'Skill: Offering'
    elif 'banner' in rl: cat = 'Skill: Banner'
    elif 'herald' in rl: cat = 'Skill: Herald'
    elif 'detonator' in rl: cat = 'Skill: Detonator'
    elif 'grenade' in rl: cat = 'Skill: Grenade'
    elif 'trap' in rl or 'mine' in rl: cat = 'Skill: Trap/Mine'
    elif 'shapeshift' in rl: cat = 'Skill: Shapeshift'
    elif 'invoc' in rl: cat = 'Skill: Invocation'
    elif 'seal' in rl: cat = 'Skill: Seal'
    elif 'remnant' in rl: cat = 'Skill: Remnant'
    elif 'infusion' in rl: cat = 'Skill: Infusion'
    elif 'meta skill' in rl: cat = 'Skill: Meta'
    elif 'empowered attack' in rl or 'ancestrally' in rl: cat = 'Skill: Empowered Attack/Ancestral'
    elif 'fissure' in rl: cat = 'Skill: Fissure'
    elif 'aftershock' in rl: cat = 'Skill: Aftershock'
    elif 'slam' in rl: cat = 'Skill: Slam'
    elif 'strike' in rl: cat = 'Skill: Strike'
    elif 'channelling' in rl: cat = 'Skill: Channelling'
    elif 'plant' in rl or 'overgrow' in rl: cat = 'Skill: Plant'
    elif 'storm' in rl or 'stag' in rl: cat = 'Skill: Storm/Stag'
    elif 'hazard' in rl: cat = 'Skill: Hazard'
    elif 'orb skill' in rl: cat = 'Skill: Orb'
    elif 'concoction' in rl: cat = 'Skill: Concoction'
    elif 'projectile' in rl or 'pierce' in rl or 'fork' in rl or 'chain' in rl: cat = 'Projectile mechanics'
    elif 'crossbow' in rl or 'bolt' in rl or 'ammunition' in rl or 'reload' in rl: cat = 'Weapon: Crossbow/Ammunition'
    elif 'quarterstaff' in rl: cat = 'Weapon: Quarterstaff'
    elif 'spear' in rl: cat = 'Weapon: Spear'
    elif 'flail' in rl: cat = 'Weapon: Flail'
    elif 'dagger' in rl: cat = 'Weapon: Dagger'
    elif 'mace' in rl: cat = 'Weapon: Mace'
    elif 'axe' in rl: cat = 'Weapon: Axe'
    elif 'sword' in rl: cat = 'Weapon: Sword'
    elif 'staff' in rl: cat = 'Weapon: Staff'
    elif 'bow' in rl and 'crossbow' not in rl: cat = 'Weapon: Bow'
    elif 'rage' in rl: cat = 'Rage mechanic'
    elif 'glory' in rl: cat = 'Glory mechanic'
    elif 'combo' in rl: cat = 'Combo mechanic'
    elif 'pin' in rl or 'pinned' in rl: cat = 'Pin mechanic'
    elif 'immobil' in rl: cat = 'Immobilise mechanic'
    elif 'heavy stun' in rl: cat = 'Heavy Stun mechanic'
    elif 'concentration' in rl: cat = 'Concentration mechanic'
    elif 'parry' in rl: cat = 'Parry mechanic'
    elif 'incision' in rl: cat = 'Incision mechanic'
    elif 'intimidat' in rl: cat = 'Intimidate mechanic'
    elif 'volatility' in rl or 'volatile power' in rl: cat = 'Volatility mechanic'
    elif 'infernal flame' in rl: cat = 'Infernal Flame mechanic'
    elif 'archon' in rl or 'arcane surge' in rl: cat = 'Archon/Arcane Surge mechanic'
    elif 'tailwind' in rl: cat = 'Tailwind mechanic'
    elif 'onslaught' in rl: cat = 'Onslaught mechanic'
    elif 'wisp' in rl or 'vivid' in rl: cat = 'Vivid Wisp mechanic'
    elif 'owl feather' in rl or 'primal bounty' in rl: cat = 'Owl Feather/Primal Bounty'
    elif 'jade' in rl: cat = 'Jade mechanic'
    elif 'rune' in rl or 'tattoo' in rl: cat = 'Rune/Tattoo mechanic'
    elif 'idol' in rl: cat = 'Idol mechanic'
    elif 'socket' in rl or 'support gem' in rl: cat = 'Socket/Gem mechanic'
    elif 'gem quality' in rl: cat = 'Gem Quality'
    elif 'reservation' in rl: cat = 'Reservation mechanic'
    elif 'charge' in rl: cat = 'Charge mechanic'
    elif 'dodge roll' in rl or 'sprint' in rl: cat = 'Movement: Dodge Roll/Sprint'
    elif 'dodge' in rl: cat = 'Dodge mechanic'
    elif 'unarmed' in rl: cat = 'Unarmed mechanic'
    elif 'dual wield' in rl or 'two-hand' in rl or 'one-hand' in rl: cat = 'Weapon type: Dual/Two/One Hand'
    elif 'shield' in rl: cat = 'Equipment: Shield'
    elif 'focus' in rl: cat = 'Equipment: Focus'
    elif 'quiver' in rl: cat = 'Equipment: Quiver'
    elif 'body armour' in rl or 'helmet' in rl or 'gloves' in rl or 'boots' in rl: cat = 'Equipment: Armour Slot'
    elif 'flask' in rl or 'charm' in rl: cat = 'Equipment: Flask/Charm'
    elif 'immune' in rl or 'unaffected' in rl or 'never' in rl: cat = 'Immunity/Unaffected'
    elif 'explode' in rl: cat = 'Explosion effect'
    elif 'converted' in rl or 'convert' in rl: cat = 'Conversion mechanic'
    elif 'damage taken' in rl: cat = 'Damage Taken modifier'
    elif 'recover' in rl: cat = 'Recovery effect'
    elif 'regenerat' in rl or 'regen' in rl: cat = 'Regeneration effect'
    elif 'gain' in rl and 'extra' in rl and 'damage' in rl: cat = 'Gain as Extra Damage'
    elif 'gain' in rl and 'damage' in rl: cat = 'Gain Damage effect'
    elif 'gain' in rl: cat = 'Gain effect'
    elif ('increased' in rl and 'damage' in rl) or ('more' in rl and 'damage' in rl) or ('reduced' in rl and 'damage' in rl) or ('less' in rl and 'damage' in rl): cat = 'DAMAGE: increased/reduced/more/less'
    elif 'damage' in rl: cat = 'DAMAGE: Other'
    elif 'attack speed' in rl: cat = 'SPEED: Attack speed'
    elif 'cast speed' in rl: cat = 'SPEED: Cast speed'
    elif 'movement speed' in rl: cat = 'SPEED: Movement speed'
    elif 'skill speed' in rl: cat = 'SPEED: Skill speed'
    elif 'critical' in rl: cat = 'CRIT: Conditional/partial'
    elif 'life' in rl and 'mana' in rl: cat = 'Life/Mana interaction'
    elif 'life' in rl: cat = 'Life-specific'
    elif 'mana' in rl: cat = 'Mana-specific'
    elif 'energy shield' in rl: cat = 'Energy Shield-specific'
    elif 'armour' in rl: cat = 'Armour-specific'
    elif 'evasion' in rl: cat = 'Evasion-specific'
    elif 'accuracy' in rl: cat = 'Accuracy-specific'
    elif 'block' in rl: cat = 'Block-specific'
    elif 'stun' in rl: cat = 'Stun-specific'
    elif 'knock' in rl: cat = 'Knockback-specific'
    elif 'resistance' in rl: cat = 'Resistance-specific'
    elif 'penetrat' in rl: cat = 'Penetration-specific'
    elif 'exposure' in rl: cat = 'Exposure-specific'
    elif 'culling' in rl: cat = 'Culling Strike-specific'
    elif 'splash' in rl: cat = 'Splash-specific'
    elif 'lucky' in rl or 'unlucky' in rl: cat = 'Lucky/Unlucky-specific'
    elif 'aggravat' in rl: cat = 'Aggravated Bleeding-specific'
    elif 'maim' in rl: cat = 'Maim-specific'
    elif 'blind' in rl: cat = 'Blind-specific'
    elif 'daze' in rl: cat = 'Daze-specific'
    elif 'wither' in rl: cat = 'Withered-specific'
    elif 'electrocute' in rl: cat = 'Electrocute-specific'
    elif 'thorns' in rl: cat = 'Thorns-specific'
    
    if cat not in cats:
        cats[cat] = []
    cats[cat].append(raw)

for cat in sorted(cats.keys()):
    items = sorted(set(cats[cat]))
    print('=== %s (%d) ===' % (cat, len(items)))
    for item in items[:5]:
        print('  %s' % item)
    if len(items) > 5:
        print('  ... and %d more' % (len(items) - 5))
    print()
